### ISSUE TITLE
Spurious dependency on ordereddict

### ISSUE THREAD

**Issue by pitrou** [testing-cabal/funcsigs#18]
The `setup.py` now inconditionally specifies a dependency on `ordereddict`, while it's only necessary for Python 2.6 and earlier.

**Comment by johanbrandhorst** [comment]
This is particularly bad for users of conda and python2.7, because conda refuses to install ordereddict with a python2.7 environment. A workaround is to manually install it using pip:

``` bash
pip install ordereddict
```

**Comment by rbtcollins** [comment]
I'm flat out travelling next week, but if someone wants to put up a PR changing this to a marker driven conditional dependency that would be great. Be sure to either set a setup_requires minimum new enough to support that, or use the hack of putting markers in extras_require.

**Comment by gnurser** [comment]
A solution here would be great.

**Comment by johanbrandhorst** [comment]
I've submitted a pull request, https://github.com/testing-cabal/funcsigs/pull/19. Does that cover everything?

**Comment by rbtcollins** [comment]
Thanks @johanbrandhorst but no - procedural code like that is incompatible with wheels - need to use PEP 508 markers instead. There's a bit of a hack to get older setuptools to handle them which I've used - see the commit that closed this for an example.

I've released 1.0.1 to get the fix out there.

**Comment by johanbrandhorst** [comment]
Great job @rbtcollins :smile:
