### ISSUE TITLE
Several links pointing to old repo / out of date read the docs

### ISSUE THREAD

**Issue by edmorley** [testing-cabal/funcsigs#24]
The "homepage" link at the bottom of https://pypi.python.org/pypi/funcsigs points to http://funcsigs.readthedocs.org/ which is out of date (still uses https://github.com/aliles/funcsigs).

Also, the README contains references to both the old repo/build status, plus the out of date read the docs page:
https://github.com/testing-cabal/funcsigs/blame/1b88d78a3883463c2d261173b959c41c9b2f3435/README.rst#L334-L351

**Comment by kamichal** [comment]
Hey! Almost three years and it's still an open issue?
