### ISSUE TITLE
_ParameterKind breaks copy.deepcopy by using keyword only constructor

### ISSUE THREAD

**Issue by elibixby** [testing-cabal/funcsigs#34]
copy.deepcopy's default reconstructor passes only positional arguments to new object constructors.

Since _ParameterKind directly looks up the "name" argument in the keyword dictionary (which is empty), any attempt to deepcopy a Parameter, BoundArguments, or Signature object will raise a KeyError.

**Comment by rbtcollins** [comment]
Does this affect CPython itself?

**Comment by elibixby** [comment]
Yes.
